version: '3'

services:
  app:
    build: app/
    tty: true
    # command: bash -c "npm install && npm run build && npm run start:app-server"
    volumes:
      - ./app:/app
    # environment:
    #   - CAROOT=/app/public/ca
    #   - NODE_EXTRA_CA_CERTS=/app/public/ca/rootCA.pem
    ports:
      - "3001:3001"