version: '3'

services:
  app:
    build: app/
    command: bash -c "npm install && npm run build && npm run generate:certificate && npm run start:app-server"
    volumes:
      - ./app:/app
    ports:
      - "3001:3001"